### ISSUE TITLE
Switch icons from Eye open/shut to something else

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#116]
Really, the eyecons aren't too great :)

**Comment by BobTorgerson** [comment]
Is this to the discretion of the person picking the new icon? Having Carolyn or someone more graphically minded weigh in their thoughts on this would be ideal

**Comment by brucecrevensten** [comment]
Good point; @carolynrosner can you pick the "on/off" icons from the [list of Favicons?](http://getbootstrap.com/components/)  I don't think we want custom icons but clearly the eye-cons don't work well here.

**Comment by BobTorgerson** [comment]
https://github.com/ua-snap/mapventure/pull/121
