### ISSUE TITLE
Sync'd maps get out of sync

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#137]
No concrete STR for this, but along these lines:

 * activate dual maps, then synchronized maps
 * activate the active fire map on both layers for reference points
 * pan and zoom the map around aggressively

After a while, it appears (Firefox) to get into a state where the maps "jitter" out of sync.

**Comment by brucecrevensten** [comment]
Just another re-confirmation, this really *does* happen fairly easily, still need minimal STR tho.

**Comment by brucecrevensten** [comment]
This may be simply a CSS issue that crops up at some point.

**Comment by BobTorgerson** [comment]
I can't recreate this problem now that we have merged the iam-map changes into master. This may be a squashed bug.

**Comment by BobTorgerson** [comment]
This does appear to have been fixed, will re-open a ticket should a regression occur.
