### ISSUE TITLE
Verify that Download Data works for Fire map

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#143]
Download data doesn't seem to work anymore.

**Comment by brucecrevensten** [comment]
Confirmed, this URL yields a 500 error.

http://mapventure.iarc.uaf.edu:8000/maps/5/immeddownload

**Comment by brucecrevensten** [comment]
It's fairly likely that the inclusion of a Remote Layer is what's breaking, here.  When you remove the VIIRS layer, it downloads OK.  (Though, it's *super* slow).

**Comment by BobTorgerson** [comment]
That is exactly correct. It looks like GeoNode breaks when it tries to download a layer that is remote, which looks like it is simply not good enough error checking on the part of GeoNode. I'm going to look into what we could do to resolve this as well as making the downloads go much faster.

**Comment by BobTorgerson** [comment]
Here is an example URL to show the 500 error that occurs in greater detail: http://mapventure.iarc.uaf.edu:8000/maps/5/download 

This is the same problem that immeddownload will have.
