### ISSUE TITLE
Display lightbox while core map is loading

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#18]
What we want to do here is to have an overlay blocking the UI until some definition of (ready) is ready.  Some things would include:

 * initial visible layers load complete
 * some sidebar prefetch...?

Goal is to prevent an incomplete-looking screen while underlying tech is loading.

**Comment by BobTorgerson** [comment]
This has been included through the PR #38: https://github.com/ua-snap/mapventure/pull/38

This can be closed once PR #38 has been merged.
