### ISSUE TITLE
Review & improve text in Fire tour

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#216]

**Comment by takurkowski** [comment]
For historical fires, we state both of these starting time periods in the tour and the info button. Determine correct one for launch (will go to 2016 now to) 1940—2015 or 1945-2015

**Comment by brucecrevensten** [comment]
Will finish this in V11 (launch candidate milestone).

**Comment by brucecrevensten** [comment]
@takurkowski I know you've started a document for this, please signal when your review is complete (chat with me to ensure we're all looking at the correct candidate material) and we will finish this as part of our last pre-launch work.

**Comment by takurkowski** [comment]
https://docs.google.com/document/d/1JULcwV6RaOxETD9CDC0QP_pbOZmijxBop0h0KS-1NlE/edit#heading=h.bos8uoa83gwl

**Comment by brucecrevensten** [comment]
One item remains: Info Sidebar for All Fires, 2017 layer.  Need the legend to finish that off.
