### ISSUE TITLE
Obtain and include the new historical fire layer which will include year 2016 via AFS's updates.

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#248]

**Comment by takurkowski** [comment]
most up to date fire history attached, also located at:
smb://hyperion.snap.uaf.edu/Data/Base_Data/GIS/GIS_Data/Vector/Fire/AFS_Fire_History_20170412
[AFS_Fire_History_20170412.zip](https://github.com/ua-snap/mapventure/files/918069/AFS_Fire_History_20170412.zip)

**Comment by brucecrevensten** [comment]
Warning about a gotcha I've encountered in GeoNode/GS -- the SLD may be nuked if you replace the layer.  So before replacing the layer, go copy/paste the style associated with the layer, then replace it once you've updated the data.
