### ISSUE TITLE
Better color ramp for Historical fires extent.

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#253]
Active fires get lost in the historical extent when both are viewed. Perhaps the current fires are active red and inactive gray while the historical are hues of orange? Might take some experimentation.

**Comment by takurkowski** [comment]
I've attached 2 sld files for colors for both the fire history and the current fires. The fire history sld has both an accurate filter and colors, but for the current fires sld, you should only use for the color, as those colors should be applied to a different input dataset.

[Archive.zip](https://github.com/ua-snap/mapventure/files/931368/Archive.zip)
