### ISSUE TITLE
Add new button called "Graph Large Fire Seasons"

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#254]
Add new button called "Graph Large Fire Seasons" which will display a temporal line plot (in a pop up window) of the cumulative area burned of the current year and the highest 5 fire seasons. Julien has this plot, it just needs to be polished a bit. This answers the question of "how bad is this year in comparison to other bad years." Data could be obtained by adding all Acres from each current polygon, or perhaps gleamed from the latest situation report.

**Comment by brucecrevensten** [comment]
Be sure that this feature is covered in the tour.

**Comment by takurkowski** [comment]
example attached, suggested changes:

- title: "Cumulative Acres Burned"
- y-axis: "Cumulative Acres Burned"
- X-axis: delete "time (days"), add some indication of where each month starts and ends. It's unclear if the label is centered on June or if the label is the beginning of June. Perhaps vertical lines pointing down on x-axis or alternating grayscale regions on background of plot?
- better line colors, perhaps have the current year as a bolder black, and the others: http://colorbrewer2.org/#type=qualitative&scheme=Accent&n=6



![daily_area_burned_counts_modif2004_2015](https://cloud.githubusercontent.com/assets/1444284/25460274/00c50218-2a8f-11e7-925b-723584ac3a18.png)
s.

**Comment by cstephen** [comment]
We have a fire graph but I still need to:
- Adjust title and labels per Tom's suggestions.
- Add the fire graph to the tour.
