### ISSUE TITLE
Bug with back button in tours

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#265]
STR: go to IAM tour; go to step titled "Comparing  Maps"; click Back.

Expected: you go back!
Actual: Tour closes

**Comment by cstephen** [comment]
@brucecrevensten Maybe this issue should be bumped to a future milestone since it's not related to the Alaska Wildfires map?

**Comment by brucecrevensten** [comment]
Oh, the same bug happens in the Fire map.  Bob has a partial fix in progress, or at least additional analysis.

**Comment by brucecrevensten** [comment]
This had a bad initial STR, but is fixed by #272.
