### ISSUE TITLE
Map's center changes after viewing info sidebar

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#273]
STR:
- open the map in a fresh state, observe the position of the center of the map
- open an Info Sidebar; it slides into place, moving the map over
- close the Info Sidebar.

Expected: map is returned to the original center position
Actual: it's tugged to the left.

My effective screen resolution is 1280x800.  I'm guessing this bug is because when the info sidebar opens, the map bumps into the actual `maxBounds` of the underlying map, causing Leaflet to trigger an "uh oh, zoom back within bounds" event.  Then the Info Sidebar, when it's closed, helpfully gets out of the way... sliding the map to where it shouldn't be.  x-ref #271 which may have already fixed this.

**Comment by BobTorgerson** [comment]
Fixed by https://github.com/ua-snap/mapventure/pull/274
