### ISSUE TITLE
Map zoom-in button zooms out on initial map load

### ISSUE THREAD

**Issue by cstephen** [ua-snap/mapventure#29]
Click the "+" on the map zoom control and it zooms out instead. But if you click layers off and on a little bit, the "+" starts working as it's supposed to again.

The "+" zoom used to work fine on initial map load. This just started happening recently.

**Comment by brucecrevensten** [comment]
...but if you add a layer, then the zoom controls are corrected!

Adding a layer heals the zoom buttons.
