### ISSUE TITLE
Make fire graph resize dynamically

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#300]
STR:

- make browser window small, open Fire map, open the Large Fire Seasons graphs
- resize your browser window to be bigger

Expected: graph resizes to take up available space
Actual: it doesn't.

This works the other way too.  It looks like we need something to listen for window resize events then fire a resize on the plot.  [This reference](https://plot.ly/javascript/responsive-fluid-layout/) may be useful.

**Comment by cstephen** [comment]
This issue is a duplicate of #298. I'll close #298 because this one has a better description.

**Comment by cstephen** [comment]
This has been fixed with #312.
