### ISSUE TITLE
Test "freebie" functionality provided by Plotly

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#306]
Idea here is to try out all the various extras that are included for free by default with Plotly -- print map, etc.  Just to understand what does or doesn't work smoothly.

**Comment by cstephen** [comment]
Here is Plotly's "freebie" toolbar:

![image](https://cloud.githubusercontent.com/assets/2566292/26082834/6dc2ddb0-397e-11e7-80be-0d7b685ff853.png)

In order, these features are:

- Download plot as a png
- Save and edit plot in cloud
- Zoom
- Pan
- Box select
- Lasso select
- Zoom in
- Zoom out
- Autoscale
- Reset axes
- Toggle spike lines
- Show closest data on hover
- Compare data on hover
- "Produced with Plotly,' which is just a link to the Plotly website

As far as I can tell, all of these features work as intended, but some do not serve any purpose or add anything meaningful to the experience. I'm planning to find a way to disable these:

- **Save and edit plot in cloud.** This is historical data. I just can't imagine a scenario where this feature would be useful for anything.
- **Box select.** This feature selects a subset of data to generate secondary plots. We are not doing anything like that with our graph, so this feature does nothing.
- **Lasso select.** Same as the box select tool. Scroll down to the bottom of [this page](https://plot.ly/javascript/lasso-selection/) to see an example of what these tools are intended for.
- **Reset axes.** This does the same thing as "Autoscale" on our graph, and I think "Autoscale" is a more intuitive name.
