### ISSUE TITLE
Perform cross browser and mobile testing before launch

### ISSUE THREAD

**Issue by cstephen** [ua-snap/mapventure#316]
- Chrome
- Firefox
- Safari
- Edge
- Internet Explorer

- iPhone
- Android

**Comment by brucecrevensten** [comment]
Here's the [browser support matrix](https://docs.google.com/spreadsheets/d/1jsT4bSqxsoHRgXtpp4nFJwwstgdfY8GEBSFGa15XiDM/edit#gid=963364027).

Here's the [test plan](https://docs.google.com/spreadsheets/d/1IpAiqGPpLPujMscB82BPFi3l704fLaqBDP9k6PgiezU/edit#gid=245130587)
