### ISSUE TITLE
Figure out an approach for layer ordering

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#33]
Being able to re-order (sort) layers makes sense.

But there's some cases where we need to think about exceptional behavior.  For example, with the NCEP data, the rasters all cover each other completely, so when you turn on a new layer in the current build, "nothing happens" -- the layer is loaded but the sort order doesn't change.

One possibility is that when activating a layer, it should immediately bubble to the top -- animate the layer transition in the layer sidebar list.

But this may not cover all use cases, we should discuss before implementing.

**Comment by BobTorgerson** [comment]
The layer ordering is very simple. You go into the Map that you want to re-order in GeoNode and click on Edit Map on the right hand box. Then click on the Edit Map button in the pop-up menu. Re-organizing the layers and then saving the map in the top left corner will result in the layers being sent to MapVenture in the reverse order that you entered them into GeoNode. 

Bruce suggests that we do a Prototype.Array.reverse (psuedocode?) to make MapVenture show the layers in the same order that GeoNode does.

**Comment by brucecrevensten** [comment]
We'll finish this in code in #44.
