### ISSUE TITLE
Make loading screen block until all resources are ready

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#334]
STR:

- Click on a map

Expected: The page shows a spinner, or "Loading, please wait!" or similar until the different async requests are all settled so that there is a smooth transition once the page is ready

Actual: it "bounces."  Parts of the app are loaded and shown immediately, but with incomplete content (background assets, descriptive blurb, etc).

It's probably OK if the map tiles continue to stream in -- perhaps there's no need to hold up the map until that's ready (?? -- not sure here) but it's jarring to have the page do a partial render then "bounce" when the async content is ready.  I think it could look better!

**Comment by cstephen** [comment]
Fixed with PR #430.
