### ISSUE TITLE
Map gets stuck dragging in Sync mode

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#359]
(Fedora 25 / Chrome 58) 

 - Go to fire map
 - Activate Dual Maps
 - Activate Sync Maps
 - drag right pane of map

Actual result: map got "stuck" (see screenshot) and out of sync

**Comment by brucecrevensten** [comment]
![screenshot from 2017-05-24 16-26-13](https://cloud.githubusercontent.com/assets/525049/26431056/c7b629c4-40a6-11e7-8832-19da0335c127.png)

**Comment by alecbennett** [comment]
Also "works" on Fedora 25 / Firefox 53.0 (64-bit)

So, maybe Linux, or maybe I'm just too aggressive with the map.

**Comment by brucecrevensten** [comment]
My hunch is that a script ends up getting laggy/stalled/killed/zombie/non-responsive because the watcher is too aggressive on sync'ing the map.  Consider a debounce if we can figure out where to inject this, or look at the options for that plugin to see if it can be improved.  Probably do this after Leaflet 1.0 is added.
