### ISSUE TITLE
Layer info button loads title from "Layers" instead of "MapLayers"

### ISSUE THREAD

**Issue by cstephen** [ua-snap/mapventure#41]
When you click the layer information button, it loads the map-agnostic version of the layer title from the `/api/layers/<layer id>` endpoint. It should instead pull the layer name from the `/api/maplayers/<map id>` endpoint to get the map-specific layer title. Or maybe we need to create a new MapLayers API endpoint to pull information for a particular layer for a particular map without grabbing all of the other map info with it.

Right now, the layer title shown in the info sidebar can be different from the one that shows up in the layer list.

**Comment by brucecrevensten** [comment]
Fixed by the changes for #45 please close this after #46 is done.
