### ISSUE TITLE
Add preliminary ability to download map

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#54]
Goal here is to explore what mechanisms GeoNode provides for downloading a map, and then tie some UI widget in MapVenture into the right API endpoint for GeoNode for doing that.

**Comment by BobTorgerson** [comment]
The preliminary ability to download maps is now available in this branch of MapVenture: https://github.com/ua-snap/mapventure/tree/download_maps

It still requires that the Cross Origin Resource Sharing be enabled until I can figure out how to allow for GeoServer to allow for Same Origin requests to be accepted. Look into that more in the future.
